export const products = [
    {
        "id": 1,
        "name": "AirPods Pro",
        "description": "Noise cancelling earbuds",
        "price": 250,
        "category": "electronics",
        "addDate": "2023-09-10",
        "rate": 4.8,
        "stock": 200,
        "soldby": "Apple",
        "img": "/products/airpod-1.webp",
        "discountPercent": 10,
        "discountedPrice": 225
    },
    {
        "id": 2,
        "name": "Bag",
        "description": "Leather stylish bag",
        "price": 150,
        "category": "fashion",
        "addDate": "2023-08-20",
        "rate": 4.3,
        "stock": 90,
        "soldby": "FashionHub",
        "img": "/products/bag-1.webp",
        "discountPercent": 15,
        "discountedPrice": 127.5
    },
    {
        "id": 3,
        "name": "Speaker",
        "description": "Wireless bluetooth speaker",
        "price": 120,
        "category": "electronics",
        "addDate": "2023-07-12",
        "rate": 4.5,
        "stock": 130,
        "soldby": "Sony",
        "img": "/products/speaker-5.webp",
        "discountPercent": 10,
        "discountedPrice": 108
    },
    {
        "id": 4,
        "name": "Product 3",
        "description": "Sample product description",
        "price": 80,
        "category": "home",
        "addDate": "2023-06-10",
        "rate": 4.0,
        "stock": 150,
        "soldby": "HomeMart",
        "img": "/products/product-3.webp",
        "discountPercent": 8,
        "discountedPrice": 73.6
    },
    {
        "id": 5,
        "name": "Product 4",
        "description": "Sample product description",
        "price": 200,
        "category": "sports",
        "addDate": "2023-05-18",
        "rate": 4.2,
        "stock": 60,
        "soldby": "Decathlon",
        "img": "/products/product-4.webp",
        "discountPercent": 12,
        "discountedPrice": 176
    },
    {
        "id": 6,
        "name": "Product 7",
        "description": "Sample product description",
        "price": 99,
        "category": "electronics",
        "addDate": "2023-09-22",
        "rate": 4.6,
        "stock": 75,
        "soldby": "Elnasr",
        "img": "/products/product-7.webp",
        "discountPercent": 10,
        "discountedPrice": 89.1
    },
    {
        "id": 7,
        "name": "Product 10",
        "description": "Sample product description",
        "price": 500,
        "category": "electronics",
        "addDate": "2023-11-05",
        "rate": 4.7,
        "stock": 40,
        "soldby": "Samsung",
        "img": "/products/product-10.webp",
        "discountPercent": 10,
        "discountedPrice": 450
    },
    {
        "id": 8,
        "name": "Product 12",
        "description": "Sample product description",
        "price": 60,
        "category": "beauty",
        "addDate": "2023-07-28",
        "rate": 4.1,
        "stock": 210,
        "soldby": "Sephora",
        "img": "/products/product-12.webp",
        "discountPercent": 20,
        "discountedPrice": 48
    },
    {
        "id": 9,
        "name": "Product 13",
        "description": "Sample product description",
        "price": 110,
        "category": "fashion",
        "addDate": "2023-12-01",
        "rate": 4.4,
        "stock": 55,
        "soldby": "Zara",
        "img": "/products/product-13.webp",
        "discountPercent": 15,
        "discountedPrice": 93.5
    },
    {
        "id": 10,
        "name": "Product 13",
        "description": "Sample product description",
        "price": 110,
        "category": "fashion",
        "addDate": "2023-12-01",
        "rate": 4.4,
        "stock": 55,
        "soldby": "Zara",
        "img": "/products/product-13.webp",
        "discountPercent": 15,
        "discountedPrice": 93.5
    },
    {
        "id": 11,
        "name": "Product 13",
        "description": "Sample product description",
        "price": 110,
        "category": "fashion",
        "addDate": "2023-12-01",
        "rate": 4.4,
        "stock": 55,
        "soldby": "Zara",
        "img": "/products/product-13.webp",
        "discountPercent": 15,
        "discountedPrice": 93.5
    },
    {
        "id": 12,
        "name": "Product 13",
        "description": "Sample product description",
        "price": 110,
        "category": "fashion",
        "addDate": "2023-12-01",
        "rate": 4.4,
        "stock": 55,
        "soldby": "Zara",
        "img": "/products/product-13.webp",
        "discountPercent": 15,
        "discountedPrice": 93.5
    },
    {
        "id": 13,
        "name": "Product 13",
        "description": "Sample product description",
        "price": 110,
        "category": "fashion",
        "addDate": "2023-12-01",
        "rate": 4.4,
        "stock": 55,
        "soldby": "Zara",
        "img": "/products/product-13.webp",
        "discountPercent": 15,
        "discountedPrice": 93.5
    },
    {
        "id": 14,
        "name": "Product 13",
        "description": "Sample product description",
        "price": 110,
        "category": "fashion",
        "addDate": "2023-12-01",
        "rate": 4.4,
        "stock": 55,
        "soldby": "Zara",
        "img": "/products/product-13.webp",
        "discountPercent": 15,
        "discountedPrice": 93.5
    },
    {
        "id": 15,
        "name": "Product 13",
        "description": "Sample product description",
        "price": 110,
        "category": "fashion",
        "addDate": "2023-12-01",
        "rate": 4.4,
        "stock": 55,
        "soldby": "Zara",
        "img": "/products/product-13.webp",
        "discountPercent": 15,
        "discountedPrice": 93.5
    },
    {
        "id": 16,
        "name": "Product 13",
        "description": "Sample product description",
        "price": 110,
        "category": "fashion",
        "addDate": "2023-12-01",
        "rate": 4.4,
        "stock": 55,
        "soldby": "Zara",
        "img": "/products/product-13.webp",
        "discountPercent": 15,
        "discountedPrice": 93.5
    },
    {
        "id": 17,
        "name": "Product 13",
        "description": "Sample product description",
        "price": 110,
        "category": "fashion",
        "addDate": "2023-12-01",
        "rate": 4.4,
        "stock": 55,
        "soldby": "Zara",
        "img": "/products/product-13.webp",
        "discountPercent": 15,
        "discountedPrice": 93.5
    },
]
